### PR TITLE
Prepare eks-rolling-update for publishing as PyPI package

### PR DESCRIPTION
**Pull request by chadlwilson**
**Motivation**

It's conventional practice in the Python community to install tools via `pip install` or equivalent, having packages published to PyPI.

It'd be really convenient to be able to `pip install` eks-rolling-update into a tooling docker image alongside kubectl etc, or locally for running without having to `git clone` etc. I think this would help with adoption, by moving to a more standard format for accessing Python tools.

**Changes**
- Introduces `setup.cfg` and `setup.py` defining the project (not done with PEP517/PEP518 `pyproject.toml` style as yet)
- Package includes an `eks_rolling_update.py` script which will be automatically put on the path after `pip install`
- Introduces `make dist`, `make dist-upload` (with [Twine](https://pypi.org/project/twine/)) for building and uploading distribution to PyPi
- Moves code under an `eksrollup` package to make it easier to package without including code in the root package
    - Backward compatibility script `eks_rolling_update.py` added
- Changes the the `.env` is located to be based on the current working directory; allowing running a module/package from a different location
- Changes the `Dockerfile` to multi-stage, building a `wheel` in a temporary layer which is installed later in the main layer. (i.e the Docker build "dog-foods" the distribution)
- Some minor tidy up of the README to improve readability and reduce duplication
- Added `deploy` step to the Travis build which runs on master and publishes to PyPI

**Testing** 
* Tested running off source with and without `.env` files
* Tested running the built package with `pip install dist/blah.whl`
* Docker build and run tested with and without `.env` files
* Tested publishing to PyPi with twine under my own account
* Tested pulling and running the PyPi package locally

**Task list**
- [x] Should the canonical name of the package be `eks-rolling-update` or `eks_rolling_update`? Which is more Pythonic
  - seems dashes is more common; left this way
- [x] Work out some automation for building and publishing to a hellofresh PyPi
  - Done in `.travis.yml` on each successful `master` build
- [X] Determine how to do versioning to support automation. Currently the version is static in `eksrollup/__version__.py`. Ideally the patch version could be automatically populated from the Travis build #, supplied via an env var.
  - Done, `major.minor` from VERSION env var in `.travis.yml`; patch from `TRAVIS_BUILD_NUMBER`
- [ ] Changelogs?

### CODE REVIEW

**Comment by crhuber** [comment]
@chadlwilson This is great!  Yeah i agree it would be much better to be able to use pip to install this. I support automating the publishing via Travis. 
@harshal-shah do you have any objections

**Comment by crhuber** [comment]
@chadlwilson had an internal discussion. We are okay to publish on py-py , there is a merge conflict. If that gets fixed up we can merge this in asap

**Comment by chadlwilson** [comment]
@crhuber yup, noted - thanks for getting back to me! I'll rebase and fix it this week some time when I get the chance.

**Comment by chadlwilson** [comment]
@crhuber I have completed the remaining work here; aside from changelogs and anything you want to do with GitHub Releases, tags etc. Updated the `.travis.yml` to automatically on successful `master` builds.

* Example uploaded from Travis: https://pypi.org/project/eks-rolling-update
* Travis build log https://travis-ci.org/github/chadlwilson/eks-rolling-update/builds/662698745

When you are ready to merge I can either delete the project from PyPi (making the name available again) or transfer ownership to you/hellofresh.

TODO on merge would be to
- [ ] Encrypt PyPI maintainer API token with `travis encrypt <api_token>` and update [./.travis.yml](https://github.com/hellofresh/eks-rolling-update/pull/36/files#diff-354f30a63fb0907d4ad57269548329e3)

**Comment by crhuber** [comment]
@chadlwilson We reviewed today and ready to merge. Thanks for the great work here. Can you remove the project from pypi so we can use the name? Then we will merge

**Comment by chadlwilson** [comment]
@crhuber Project removed now - merge at will! 🎉

**Comment by chadlwilson** [comment]
Thanks a lot - we are now using this successfully in our pipelines. Used it to roll to Amazon's latest EKS AMIs this morning.

**Pull request merged**
