### PR TITLE
Adding changes to exclude nodes in k8s managed by spotinst

### PR DESCRIPTION
**Pull request by akshaychitneni**
fixes https://github.com/hellofresh/eks-rolling-update/issues/17

### CODE REVIEW

**Comment by crhuber** [comment]
Thanks will test it this week

**Comment by crhuber** [comment]
@akshaychitneni theres a couple conflicts if you could please resolve then i will merge it in, thanks

**Comment by akshaychitneni** [comment]
sorry for the delay. Resolved conflicts

**Comment by js-timbirkett** [comment]
This addition breaks RUN_MODE 2, possibly others.

**Comment by js-timbirkett** [comment]
After trying with `RUN_MODE` set to 1, this just seems broken 🤔

**Pull request merged**
