### PR TITLE
Provide casting for values from env

### PR DESCRIPTION
**Pull request by mbrannigan**

### CODE REVIEW

**Comment by chadlwilson** [comment]
Hi @crhuber - thanks for this useful tool!

Any chance of getting this PR merged? This would seem to fix #26 which is making the env config overrides unusable at the moment.

**Comment by crhuber** [comment]
thanks @mbrannigan

**Comment by mbrannigan** [comment]
You're welcome!  Thank you so much for the script.  It's been extremely helpful.

**Comment by chadlwilson** [comment]
Thanks again @crhuber - this tool is super valuable for those of us who can't use managed node groups for one reason or another :)

**Comment by TBeijen** [comment]
Doesn't the failing build need looking into? Or is it perhaps because build configuration in branch not being up to date?

**Pull request merged**
