### PR TITLE
Adding Mode 4  (rolling nodes based on age)

### PR DESCRIPTION
**Pull request by sarmad-abualkaz**
@crhuber This is a continuation of splitting #35 into multiple PRs.

This PR adds a mode 4 to the script which aims to roll nodes based on each ec2 instance's age (i.e. roll nodes older than x days). A new variable is added `MAX_ALLOWABLE_NODE_AGE` which defaults to 6 days as part of this new mode. The new mode checks for each instance launch date and replaces nodes older than `MAX_ALLOWABLE_NODE_AGE`. The purpose behind this is to ensure nodes running in a cluster are consistently refreshed regardless of configuration changes. 

Mode 4 follows the same pattern as mode 1 in order of execution: scale up and cordon the outdated nodes of each ASG one-by-one, before each is drained.

### CODE REVIEW

**Comment by jgournet** [comment]
@crhuber :
Any chance this can be looked and merged ? this is the mode we are really looking for

**Comment by crhuber** [comment]
@sarmad-abualkaz thanks for the PR. Sorry for the delay. Just out of curiosity, what your use case here?

**Comment by TBeijen** [comment]
Can't speak for @sarmad-abualkaz , but I thing I myself have been considering is: A mechanism to peridocally (e.g. nightly) replace oldest nodes with new ones. This PR combined with #42 allows doing that with this tool.

**Comment by sarmad-abualkaz** [comment]
> Can't speak for @sarmad-abualkaz , but I thing I myself have been considering is: A mechanism to peridocally (e.g. nightly) replace oldest nodes with new ones. This PR combined with #42 allows doing that with this tool.

We use this mode for the same purpose as well (nightly roll all nodes in cronJob setup). We're also using a helm chart to configure the jobs on a maintenance cluster, I can contribute that chart here if anyone's interested.

I'm just curious @TBeijen, how do you roll all nodes using this script on the same cluster (I mean w/o impacting the node running the script itself?) We have gone for the option of running the job on a different cluster than the nodes being rolled.

**Comment by TBeijen** [comment]
> I'm just curious @TBeijen, how do you roll all nodes using this script on the same cluster (I mean w/o impacting the node running the script itself?) We have gone for the option of running the job on a different cluster than the nodes being rolled.

We haven't implemented it. And yes, that particular challenge crossed my mind as well. 

Thought that comes to mind: Precede with job that (similar to eks-rolling-update) determines what nodes are 'old', then patches the eks-rolling-update job with `NodeAffinity` to exclude those nodes.

Extra moving part is not ideal. Would probably work, wondering if it would still require a safe-guard in eks-rolling-update to exclude the node it's scheduled on itself. Food for thought...

**Pull request merged**
